# Generated by Django 5.1.2 on 2024-10-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixed', '0003_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiLanguageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=20)),
                ('title_en', models.CharField(max_length=20)),
                ('text_ru', models.TextField()),
                ('text_en', models.TextField()),
            ],
        ),
    ]
